# Site settings
title: Kirsten O'Farrell
email: kirsten.ofarrell@gmail.com
subtitle: "My website for you."
url: "http://www.kirstenofarrell.com" # the base hostname & protocol for your site
baseurl: "/kirstenofarrell-dot-com"
twitter_username: kirstenofarrell
github_username:  abadfish

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
